trigger:
- main

pool:
  name: AzurePipelines  # Use the name of your self-hosted agent pool  


variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: 'Restore dependencies'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test
  displayName: 'Run tests'

- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish the build'
